### ISSUE TITLE
Retrieve most recent contextionary on startup of verification script

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate-infra#29]
This is basically a copy of https://github.com/creativesoftwarefdn/weaviate/issues/595. The difference being that we want the same behavior for the verification/benchmark script as well.

## Todos
* [x] If no flag is set, download the latest contextionary
* [x] Remove contextionary which is committed into the script repo
* [x] let the user over-write the version to be downloaded via CLI flag.
* [x] remove temporary filters (workaround) which would only allow uppercase words for class names. The new contextionary is now always lowercase and we can uppercase whichever words we want.
